### PR TITLE
Documentation updates after docker compose changes

### PR DESCRIPTION
**Pull request by shimilgithub**
-  #836 
-  Includes changes in documentation after separating it into `docker-compose-staging` and `docker-compose-production`

### CODE REVIEW

**Comment by AthulyaMS** [comment]
I didnt see a comand to down docker compose ,do we need to add that .

docker compose -f docker-compose-production.yml --profile deployment --env-file prod.env down

The above command was worked in production to down compose .If this is needed ,update in staging also

**Comment by shimilgithub** [comment]
> I didnt see a comand to down docker compose ,do we need to add that .
> 
> docker compose -f docker-compose-production.yml --profile deployment --env-file prod.env down
> 
> The above command was worked in production to down compose .If this is needed ,update in staging also

can you point to the right place in PR?

**Comment by AthulyaMS** [comment]
Actually, in the documentation, I can't see how to down the Docker Compose. I was asking for a suggestion: should we add a command to bring down the Compose file?

**Comment by shimilgithub** [comment]
> docker compose -f docker-compose-production.yml --profile deployment --env-file prod.env down

updated

**Review by AthulyaMS — APPROVED** [review]

**Pull request merged**
